on: [push]
name: Test, Build and Release apk
jobs:
  build:
    name: Build apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Build 
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.1'
          channel: 'stable'
      - run: |
          pwd
          echo $GITHUB_WORKSPACE
          flutter pub get
          flutter test
          flutter build apk --split-per-abi
      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}
